### PR TITLE
Fix wording

### PR DESCRIPTION
**Pull request by btosic**
Fix wording for 'having information but does necessarily mean understand it'

### CODE REVIEW

**Review by orcmid — APPROVED** [review]
Wow that's a great paragraph.  I have only examined the replacement since the GitHub DIFF granularity is so coarse.  The change appears to be acceptable.

[Meta-consideration] Does the form of markdown here provide for line breaks internal to paragraphs so that changes and edits can be localized better (and the the raw text be displayed better in some cases).  I get that there are conflicting usability aspects in this.]

**Comment by btosic** [comment]
> [Meta-consideration] Does the form of markdown here provide for line breaks internal to paragraphs so that changes and edits can be localized better (and the the raw text be displayed better in some cases). I get that there are conflicting usability aspects in this.]

I think the paragraph in this change doesn't have internal line breaks so the whole paragraph is formally one line. That's the reason we see it completely marked as change in GitHub comparison. Inside a paragraph, I only updated the phrase which started with 'having information but does necessarily..."

**Comment by orcmid** [comment]
> > [Meta-consideration] ...

> I think the paragraph in this change doesn't have internal line breaks so the whole paragraph is formally one line. That's the reason we see it completely marked as change in GitHub comparison. Inside a paragraph,...

Yes, on reflection, the meta-consideration isi about `Peruse` and also about Amy Ko's chosen form for entering paragraphs.  I realize that one cannot do anything about paragraphs in single lines, something our text editors might reflow but are tough to examine in "raw."  The unintended consequence has to do with how (GitHub) DIFF comparisons are tied to the raw-text line level.

I notice that the raw files we are looking at do have blank lines between paragraphs, and those matter for the GitHub rendering of these Markdown pages.  What I can't tell here is whether or not that matters for Peruse, although the Peruse tutorial document also has such blank lines.  Breaking up a paragraph into multiple raw-text lines as part of making changes in a pull-request makes incidental changes that are probably objectionable, not achieving any useful DIFF improvement at all.  A quandary.

For some of these questions,  I think it is necessary to install peruse and see how it renders the tutorial document in HTML.  Looking at its files via GitHub Markdown rendering does not answer these and other questions.

I realize that this discussion is not useful here, and I may have to put it in a Discussion topic somewhere.

**Comment by amyjko** [comment]
Thanks for the edit Bojan!

Re: Peruse, the flavor of Markdown I wrote does preserve intra-paragraph line breaks, since they're often useful for formatting. So reformatting to make diffs more obvious would break the layout. (I optimized for the reader UX over the writer UX, especially since most writers won't be using GitHub to write, or be versioning their writing). If I ever get around to creating a backend for Peruse, more legible diffs and versioning would be a nice feature.

**Pull request merged**
