### PR TITLE
rename chapters with numeric prefixes

### PR DESCRIPTION
**Pull request by sudoer**
Naming the chapter files with numeric prefixes makes it a little easier to work on or to read, if you're trying to work through the chapters in order.

Plus, it's a great illustration of the importance of meta-data.  :-D

### CODE REVIEW

**Comment by amyjko** [comment]
Good idea! I hadn't designed for people reading in plain text, but there's no harm in this.

One note about the pull request: there are chapter citations throughout (e.g., `[Designing Information|design]`, so this rename would break all of this references.

**Comment by amyjko** [comment]
Thanks for this! However, I realized there are three issues with renames:

* The chapter IDs appear in the URL, and so there is an aesthetic implication of the URL. The current names with no chapter numbers have a relatively clean set of paths, but these numbers would clutter them
* Because the book can evolve, I may write more chapters in the future. This would require renumbering all subsequent chapters.
* Many people have linked to the book's chapters on their own websites (including my own course website), and so this would break all of those links.

The only way I can think of to avoid those problems is to have some convention of allowing numbered files, but stripping them from the URLs. That's kind of kludgey.

Hmmm...

**Comment by sudoer** [comment]
Yep... sounds like a good reason to keep it the same.  But at least fix that designing link in chapter 18.

~ alan

**Comment by amyjko** [comment]
Thanks for finding that broken link! I'll stew on ways to encode ordering in the files.

**Pull request closed without merging**
